const {
  MONGODB_URL,
  PORT,
  ACCESS_TOKEN,
  REFRESH_TOKEN,
  REDIS_PORT,
  REDIS_HOST,
  MAILTRAP_USERNAME,
  MAILTRAP_PASSWORD,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
} = process.env;

if (
  !MONGODB_URL ||
  !PORT ||
  !ACCESS_TOKEN ||
  !REFRESH_TOKEN ||
  // !REDIS_HOST ||
  !REDIS_PORT ||
  !MAILTRAP_PASSWORD ||
  !MAILTRAP_PASSWORD ||
  !CLOUDINARY_CLOUD_NAME ||
  !CLOUDINARY_API_KEY ||
  !CLOUDINARY_API_SECRET
) {
  console.log("Environment Variables are not set");
  process.exit(1);
}
